### ISSUE TITLE
solidweb.me appears to be down

### ISSUE THREAD

**Issue by Vinnl** [serverproject-dev/solidweb.me#1]
Getting a 502 Bad Gateway error at the time of writing:

https://downforeveryoneorjustme.com/solidweb.me

(Heads-up for @ewingson I think?)

**Comment by ewingson** [comment]
Thank you @Vinnl.
I've restarted the service and its up again.
This comes (I guess) cause I didn't harden and stealth it enough (maybe  
the user running the server process must be adjusted)

for now I'm restarting manually.

ewingson


Am 01.09.2023, 10:17 Uhr, schrieb Vincent ***@***.***>:

> Getting a 502 Bad Gateway error at the time of writing:
>
> https://downforeveryoneorjustme.com/solidweb.me
>
> (Heads-up for @ewingson I think?)
>


-- 
Matthias ***@***.***)

**Comment by ewingson** [comment]
up again.
https://solidweb.me/somewhereelse/index.html
https://downforeveryoneorjustme.com/solidweb.me

**Comment by Vinnl** [comment]
Thank you!

**Comment by NSeydoux** [comment]
This issue happened again. I opened an issue on https://gitlab.com/solidweb.me/support/-/issues/4, is it the appropriate place?

**Comment by ewingson** [comment]
yes Nicolas, right place.
recently I started to use pm2 to avoid these downtimes.
the service seems to have restarted automatically, seen from here  
everything appears up.

let me know, if the issue persists.
-- 
Matthias ***@***.***)

Am 22.09.2023, 16:40 Uhr, schrieb Zwifi ***@***.***>:

> This issue happened again. I opened an issue on  
> https://gitlab.com/solidweb.me/support/-/issues/4, is it the appropriate  
> place?
