### ISSUE TITLE
counter-actions concerning regular 502s (Bad Gateway), implementing pm2 and 7.0.4?

### ISSUE THREAD

**Issue by ewingson** [serverproject-dev/solidweb.me#2]
- [x] doing an evaluation of the situation (sync)
- [x] make `pm2` work (I have an account on https://pm2.io/ and I have an archived command which I am not sure if it's correct) (async?)
- [x] maybe with these steps the existence of the insecure System Unit user already loses its importance
- [x] if we're really good, maybe updating solidweb.me to 7.0.4 (bonus)
- [x] designing a usable `index.html` with all necessary information for existing users as well as info to sign-up (cherry-on-top, feel educated enough to do this alone)

**Comment by mrkvon** [comment]
@ewingson I started documenting how to set up CSS (my opinionated way) at https://github.com/mrkvon/css-setup. It's still largely unfinished and untested. I'll notify here when it's ready.

**Comment by mrkvon** [comment]
Finished writing the instructions and tested them. It works. I'll be interested in hearing your feedback if you try it out @ewingson

**Comment by ewingson** [comment]
I got pm2 running on teamid.live (actual 7.0.5) as well. and don't worry, we can always keep solidweb.me running into eternity. but gotta keep track of my life responsibilities now for a while.
